<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.14">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Evaluating the Randomness of a Minigame Selection System</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7832d8100c30e5308af25d4a964213de.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-7838bb9118963e4952631d2de9ced9f2.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Evaluating the Randomness of a Minigame Selection System</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>Random selection is a common mechanic in video games, and perceived unfairness in supposedly random systems can affect player trust, even if there is no true bias. This study examined the minigame selection in the video game <em>Hypixel Party Games</em> to determine whether the system followed an expected uniform distribution assuming random selection. Data were collected across 10 trials, yielding a combined sample of 3,318 games, each involving a random selection of 8 of 26 possible minigames. A chi-square goodness of fit test was used to assess whether minigame selection followed a uniform distribution, along with a Monte Carlo simulation to correct for the dependence introduced by the without-replacement selection process. Exploratory analyses used chi-square tests of independence to examine potential associations between minigame selection and slot position or hour of day. The results revealed that there were no significant results for the combined dataset (corrected <span class="math inline">\(p\)</span> = 0.1676) and individual trial analyses (corrected <span class="math inline">\(p\)</span> range: 0.0780-0.6658) at <span class="math inline">\(\alpha\)</span> = 0.05. Negligible effect sizes were also reported for the combined dataset (<span class="math inline">\(w_{obs}\)</span> = 0.0293), landing in the 83.24th percentile of simulated tests. Exploratory analyses found a statistically significant but negligible association between slot position and minigame selection (Cramér’s <span class="math inline">\(V\)</span> = 0.0346), and no significant association with hour of day. These findings suggest that the selection of minigames appears to be consistent with genuine random sampling.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1 Introduction</h2>
<p>Randomness is an essential component of many modern video games. From determining item spawns to selecting maps and minigames, randomization majorly influences an individual’s overall experience with a video game. Since random processes can produce streaks and uneven outcomes, the human mind may interpret that as meaning certain outcomes appear more than others; however, it can be difficult to determine whether these patterns are a result of actual bias or simply chance. This is where statistics becomes essential, as it provides objective methods for determining whether the observed patterns are from bias or random variation.</p>
<p>One application of this question is in the video game <em>Hypixel Party Games</em>, where players have speculated whether certain minigames were selected more than others. This video game features 26 possible minigames, of which 8 are selected per game session, each theoretically having an equal chance of being selected. Throughout this paper, <em>game</em> refers to one such match rather than the video game itself. Using 10 independent samples with around 325 games (2600 minigame selections) per sample, this analysis tests whether the observed distribution is consistent with this expectation. If the video game’s selection was random, each minigame should appear at the expected frequency over a large amount of games. The hypotheses are:</p>
<ul>
<li><strong>Null hypothesis (<span class="math inline">\(H_0\)</span>)</strong>: The distribution of minigame selections follows the expected uniform distribution under random selection.</li>
<li><strong>Alternate hypothesis (<span class="math inline">\(H_1\)</span>)</strong>: The distribution of minigame selections differs from the expected uniform distribution under random selection.</li>
</ul>
</section>
<section id="methodology" class="level2">
<h2 class="anchored" data-anchor-id="methodology">2 Methodology</h2>
<p>This study investigated whether the minigame selection in <em>Hypixel Party Games</em> produces outcomes that are consistent with a uniform random distribution. Data were collected across 10 independent trials. The sequence of minigames selected in each game was extracted using optical character recognition (OCR); then, it was cleaned and compiled into a structured dataset. The dataset was then analyzed in Python using a chi-square goodness of fit test, corrected using a Monte Carlo simulation due to the non-independent variables.</p>
<section id="data-collection" class="level3">
<h3 class="anchored" data-anchor-id="data-collection">2.1 Data Collection</h3>
<p>Data were collected over multiple gameplay sessions and organized into 10 different independent trials. To maximize the number of games collected within a feasible timeframe, the data were collected by entering a game session, waiting for the game to start, and then leaving without playing repeatedly for around 325 games. After all of the games were collected, the replay feature on <em>Hypixel</em> was utilized in order to determine the 8 minigames chosen in each individual game. This approach avoided the time cost of completing all 8 minigames per game while still efficiently collecting the full minigame sequence.</p>
<p>An automated data collection was programmed in order to reduce manual transcription and improve accuracy. The program used OCR to extract the minigame names displayed on screen during each replay. To ensure the accuracy of the OCR, extracted text was validated against a reference list of each of the 26 possible minigame names; any output that did not match an entry in this list was flagged as an OCR error and corrected manually. Since the minigame names are very visually distinct from each other, the risk of one minigame being misclassified as another is unlikely. Finally, for each minigame, the trial number, game number, slot number, timestamp, and selected minigame were recorded in a comma-separated values (CSV) file, allowing use for statistical analysis in Python.</p>
<p>Before analysis, the data from the CSV was imported into the pandas library from Python in order to clean the data before statistical testing. The dataset was inspected for missing, duplicate, and invalid records. Any incomplete or incorrectly recorded games were removed before statistical testing. After removing 44 incomplete or incorrectly recorded games, 3,318 games remained for statistical analysis, representing 26,544 individual minigame observations (3,318 games <span class="math inline">\(\times\)</span> 8 minigames per game).</p>
</section>
<section id="dataset-structure" class="level3">
<h3 class="anchored" data-anchor-id="dataset-structure">2.2 Dataset Structure</h3>
<p>The collected data was organized into a CSV file containing the following columns:</p>
<div id="tbl-dataset-structure" class="striped quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dataset-structure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Dataset Structure and Description of Variables
</figcaption>
<div aria-describedby="tbl-dataset-structure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 77%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Column Name</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>trial</strong></td>
<td style="text-align: left;">The trial in which the game was recorded.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>game_number</strong></td>
<td style="text-align: left;">The sequential game number within each trial.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>slot</strong></td>
<td style="text-align: left;">The position of the minigame within the game (1-8).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>timestamp</strong></td>
<td style="text-align: left;">The recorded start time of the game.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>minigame</strong></td>
<td style="text-align: left;">The name of the selected minigame.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Each row represents one minigame observation. This format preserved the original data while making it easier to summarize, filter, and analyze the data.</p>
</section>
<section id="statistical-analysis" class="level3">
<h3 class="anchored" data-anchor-id="statistical-analysis">2.3 Statistical Analysis</h3>
<p>The language Python was used along with the libraries numpy and pandas for the statistical analysis. Analyses were performed at two different levels: separately for each of the 10 individual trials, and for the combined dataset across all trials. This allowed for an assessment of consistency across individual trials as well as an overall test using the full combined sample.</p>
<p>Consistent with the hypotheses above, the null hypothesis states that each of the 26 minigames is equally likely to be chosen, meaning that <span class="math inline">\(p_i = 1/26\)</span> for <span class="math inline">\(i = 1,...,26\)</span>, while the alternate hypothesis states that at least one minigame has a selection probability of <span class="math inline">\(p_i \neq 1/26\)</span>. These hypotheses were evaluated separately for each individual trial and for the combined dataset. A significance level of <span class="math inline">\(\alpha = 0.05\)</span> was used in all tests.</p>
<section id="chi-square-goodness-of-fit-testing" class="level4">
<h4 class="anchored" data-anchor-id="chi-square-goodness-of-fit-testing">2.3.1 Chi-Square Goodness Of Fit Testing</h4>
<p>A chi-square goodness of fit was utilized in order to compare whether the observed distribution significantly differs from <span class="math inline">\(H_0\)</span>:</p>
<p><span class="math display">\[
\chi^2 = \sum_{i=1}^{26} \frac{(O_i - E_i)^2}{E_i}
\]</span></p>
<p>where <span class="math inline">\(O_i\)</span> represents the observed times minigame <span class="math inline">\(i\)</span> was selected, and <span class="math inline">\(E_i\)</span> is the expected count under <span class="math inline">\(H_0\)</span>. For a sample of <span class="math inline">\(N\)</span> games, the expected count for each minigame in this experiment would be <span class="math inline">\(E_i = N \times 8/26\)</span>.</p>
<p>The standard chi-square goodness of fit test assumes that each and every observation is fully independent. However, this assumption does not apply to this experiment, as 8 minigames are chosen from 26 minigames without replacement. This introduces dependent observations into the statistical test, reducing the variation within the distribution, causing the value of the chi-square statistic (<span class="math inline">\(\chi^2\)</span>) to decrease while inflating the standard p value.</p>
</section>
<section id="monte-carlo-correction-for-dependence" class="level4">
<h4 class="anchored" data-anchor-id="monte-carlo-correction-for-dependence">2.3.2 Monte Carlo Correction for Dependence</h4>
<p>In order to account for this, a Monte Carlo simulation was performed to approximate the value of <span class="math inline">\(\chi^2\)</span> performed under the null hypothesis. The simulation repeatedly generated <span class="math inline">\(N\)</span> simulated games (100,000 iterations per test), where <span class="math inline">\(N\)</span> matched the sample size of the trial or combined dataset being tested. Each simulated game consisted of 8 minigames drawn without replacement from the 26 total options, mirroring the actual selection process. A random seed value of 42 was used in numpy across all simulations to ensure consistency and reproducibility. The corrected p value was then calculated by comparing the amount of simulated <span class="math inline">\(\chi^2\)</span> values that were greater than or equal to the actual observed chi-square value:</p>
<p><span class="math display">\[
p = \frac{(\text{number of simulated } X^2 \geq X^2_{obs}) + 1}{100,000 + 1}
\]</span></p>
<p>This corrected p value accounts for the dependence between minigame selections (a hypergeometric-type process) within a game, unlike the standard chi-square p value, which assumes independence.</p>
</section>
<section id="effect-size-cohens-w" class="level4">
<h4 class="anchored" data-anchor-id="effect-size-cohens-w">2.3.3 Effect Size (Cohen’s <span class="math inline">\(w\)</span>)</h4>
<p>To calculate the effect size, the same Monte Carlo simulation values were used to evaluate the effect size. The observed Cohen’s <span class="math inline">\(w\)</span> was calculated as:</p>
<p><span class="math display">\[
w = \sqrt{\frac{\chi^2}{N}}
\]</span></p>
<p>where <span class="math inline">\(\chi^2\)</span> is the observed chi-square statistic and <span class="math inline">\(N\)</span> is the number of observations. Each simulated chi-square value was similarly converted into a <span class="math inline">\(w\)</span> value, creating a null distribution of expected effect sizes under <span class="math inline">\(H_0\)</span>. The observed <span class="math inline">\(w\)</span> was then reported as a percentile within the simulated distribution to determine the magnitude of the observed effect size relative to <span class="math inline">\(H_0\)</span>.</p>
</section>
<section id="exploratory-analyses" class="level4">
<h4 class="anchored" data-anchor-id="exploratory-analyses">2.3.4 Exploratory Analyses</h4>
<p>In addition to the analyses described above, exploratory analyses were conducted to examine whether minigame selections were impacted by slot position (1-8) or the hour of day during which the game was played. Since these analyses were exploratory, no correction for multiple comparisons was applied. These relationships were evaluated using the chi-square test of independence, being applied to contingency tables of slot position by minigame and hour of day by minigame, respectively. Unlike the goodness of fit test explained above for the main analysis, this test evaluates whether two categorical variables are associated with one another. Effect size for these tests was quantified using Cramér’s <span class="math inline">\(V\)</span>:</p>
<p><span class="math display">\[
V = \sqrt{\frac{\chi^2}{N(k-1)}}
\]</span></p>
<p>where <span class="math inline">\(N\)</span> represents the total number of observations, and <span class="math inline">\(k\)</span> is the smaller number of row or column categories in the contingency table. As with the primary analysis, the dependent aspect within the minigame selection process introduces issues with using the chi-square test of independence; however, due to the exploratory nature of these analyses, this dependence was not further corrected for in this report.</p>
</section>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">3 Results</h2>
<section id="descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics">3.1 Descriptive Statistics</h3>
<p>Data were collected across 10 independent trials, yielding a final sample of <span class="math inline">\(N\)</span> = 3318 total games. Individual trial sample sizes ranged from 322 to 342 games. Across the combined dataset, individual minigame selection counts ranged from 961 to 1079 (<span class="math inline">\(M\)</span> = 1020.92, <span class="math inline">\(SD\)</span> = 30.52), out of an expected count of <span class="math inline">\(E = N \times 8/26\)</span> under uniform random selection.</p>
<div id="tbl-descriptive" class="striped quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-descriptive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Descriptive Statistics for Individual and Combined Trials
</figcaption>
<div aria-describedby="tbl-descriptive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 22%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Trial</th>
<th style="text-align: right;">Games</th>
<th style="text-align: right;">Observations</th>
<th style="text-align: right;">Min Count</th>
<th style="text-align: right;">Max Count</th>
<th style="text-align: right;">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>1</strong></td>
<td style="text-align: right;">322</td>
<td style="text-align: right;">2576</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">116</td>
<td style="text-align: right;">99.08</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>2</strong></td>
<td style="text-align: right;">339</td>
<td style="text-align: right;">2712</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">124</td>
<td style="text-align: right;">104.31</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>3</strong></td>
<td style="text-align: right;">334</td>
<td style="text-align: right;">2672</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">121</td>
<td style="text-align: right;">102.77</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>4</strong></td>
<td style="text-align: right;">342</td>
<td style="text-align: right;">2736</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">122</td>
<td style="text-align: right;">105.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>5</strong></td>
<td style="text-align: right;">333</td>
<td style="text-align: right;">2664</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">102.46</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>6</strong></td>
<td style="text-align: right;">329</td>
<td style="text-align: right;">2632</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">117</td>
<td style="text-align: right;">101.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>7</strong></td>
<td style="text-align: right;">330</td>
<td style="text-align: right;">2640</td>
<td style="text-align: right;">86</td>
<td style="text-align: right;">130</td>
<td style="text-align: right;">101.54</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>8</strong></td>
<td style="text-align: right;">328</td>
<td style="text-align: right;">2624</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">115</td>
<td style="text-align: right;">100.92</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>9</strong></td>
<td style="text-align: right;">334</td>
<td style="text-align: right;">2672</td>
<td style="text-align: right;">91</td>
<td style="text-align: right;">139</td>
<td style="text-align: right;">102.77</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>10</strong></td>
<td style="text-align: right;">327</td>
<td style="text-align: right;">2616</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">100.62</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Combined</strong></td>
<td style="text-align: right;">3318</td>
<td style="text-align: right;">26544</td>
<td style="text-align: right;">961</td>
<td style="text-align: right;">1079</td>
<td style="text-align: right;">1020.92</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="primary-analysis-randomness-of-combined-trials" class="level3">
<h3 class="anchored" data-anchor-id="primary-analysis-randomness-of-combined-trials">3.2 Primary Analysis: Randomness of Combined Trials</h3>
<p>A chi-square goodness of fit was conducted on the combined dataset (3318 games, yielding 26544 minigame selections) to evaluate whether minigame selection frequencies deviated from <span class="math inline">\(H_0\)</span>. The observed chi-square statistic was <span class="math inline">\(\chi^2\)</span> = 22.81 with an uncorrected p value of <span class="math inline">\(p\)</span> = 0.5889; however, as stated in Section 2.3.1, this uncorrected value is inaccurate because the standard chi-square assumes complete independent observations. A Monte Carlo simulation was used to correct the p value to <span class="math inline">\(p\)</span> = 0.1676, indicating no evidence against the null hypothesis at <span class="math inline">\(\alpha\)</span> = 0.05.</p>
<p>The effect size was quantified by using Cohen’s <span class="math inline">\(w\)</span> (<span class="math inline">\(w_{obs}\)</span> = 0.0293), calculated using <span class="math inline">\(N\)</span> = 26544 total minigame selections. To account for the same dependence structure, <span class="math inline">\(w_{obs}\)</span> was compared to a null distribution of expected effect sizes under <span class="math inline">\(H_0\)</span>, with <span class="math inline">\(\bar{w}_{sim}\)</span> = 0.0258 and <span class="math inline">\(SD\)</span> = 0.0037. This resulted in a standardized effect of <span class="math inline">\(z_w\)</span> = 0.9654, corresponding to the 83.24th percentile, which is consistent with the non-significant corrected p value.</p>
</section>
<section id="secondary-analysis-consistency-across-individual-trials" class="level3">
<h3 class="anchored" data-anchor-id="secondary-analysis-consistency-across-individual-trials">3.3 Secondary Analysis: Consistency Across Individual Trials</h3>
<p>To assess whether <span class="math inline">\(H_0\)</span> was consistently supported across independent samples, all of the tests were computed separately for each of the 10 trials as described in Section 2.3 and displayed under Table 3. None of the 10 individual trials produced a statistically significant deviation from uniform minigame selection at <span class="math inline">\(\alpha\)</span> = 0.05 (corrected <span class="math inline">\(p\)</span> range: 0.0780-0.6658).</p>
<p>The standardized effect sizes (<span class="math inline">\(z_w\)</span>) ranged from -0.4442 (Trial 3, 33.47th percentile) to 1.4415 (Trial 9, 92.23rd percentile). Both of these trials remain well within the range expected under random sampling variability, assuming a threshold of <span class="math inline">\(|z_w| &gt; 2\)</span>. Given that 10 independent trials were conducted at <span class="math inline">\(\alpha\)</span> = 0.05, fewer than one trial (~0.46) would be expected to exceed <span class="math inline">\(|z_w| &gt; 2\)</span> purely by chance assuming the null distribution. There were no trials exceeding this threshold, supporting the conclusion that individual trials behaved consistently with <span class="math inline">\(H_0\)</span>, rather than the combined result being driven by an anomalous individual trial.</p>
<div id="tbl-trials-analysis" class="striped quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-trials-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Statistics for Individual Trials
</figcaption>
<div aria-describedby="tbl-trials-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Trial</th>
<th style="text-align: right;"><span class="math inline">\(\chi^2\)</span></th>
<th style="text-align: right;"><span class="math inline">\(p\)</span></th>
<th style="text-align: right;"><span class="math inline">\(p_{corr}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(w_{obs}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(z_w\)</span></th>
<th style="text-align: right;">Percentile</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>1</strong></td>
<td style="text-align: right;">18.59</td>
<td style="text-align: right;">0.8163</td>
<td style="text-align: right;">0.4189</td>
<td style="text-align: right;">0.0850</td>
<td style="text-align: right;">0.1843</td>
<td style="text-align: right;">58.22</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>2</strong></td>
<td style="text-align: right;">23.06</td>
<td style="text-align: right;">0.5739</td>
<td style="text-align: right;">0.1592</td>
<td style="text-align: right;">0.0922</td>
<td style="text-align: right;">1.0073</td>
<td style="text-align: right;">84.15</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>3</strong></td>
<td style="text-align: right;">15.50</td>
<td style="text-align: right;">0.9290</td>
<td style="text-align: right;">0.6658</td>
<td style="text-align: right;">0.0762</td>
<td style="text-align: right;">-0.4442</td>
<td style="text-align: right;">33.47</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>4</strong></td>
<td style="text-align: right;">16.35</td>
<td style="text-align: right;">0.9040</td>
<td style="text-align: right;">0.5939</td>
<td style="text-align: right;">0.0773</td>
<td style="text-align: right;">-0.2611</td>
<td style="text-align: right;">40.68</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>5</strong></td>
<td style="text-align: right;">19.31</td>
<td style="text-align: right;">0.7821</td>
<td style="text-align: right;">0.3656</td>
<td style="text-align: right;">0.0851</td>
<td style="text-align: right;">0.3231</td>
<td style="text-align: right;">63.52</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>6</strong></td>
<td style="text-align: right;">18.16</td>
<td style="text-align: right;">0.8354</td>
<td style="text-align: right;">0.4507</td>
<td style="text-align: right;">0.0831</td>
<td style="text-align: right;">0.1037</td>
<td style="text-align: right;">55.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>7</strong></td>
<td style="text-align: right;">24.19</td>
<td style="text-align: right;">0.5083</td>
<td style="text-align: right;">0.1183</td>
<td style="text-align: right;">0.0957</td>
<td style="text-align: right;">1.1985</td>
<td style="text-align: right;">88.20</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>8</strong></td>
<td style="text-align: right;">15.71</td>
<td style="text-align: right;">0.9231</td>
<td style="text-align: right;">0.6478</td>
<td style="text-align: right;">0.0774</td>
<td style="text-align: right;">-0.3979</td>
<td style="text-align: right;">35.33</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>9</strong></td>
<td style="text-align: right;">25.60</td>
<td style="text-align: right;">0.4293</td>
<td style="text-align: right;">0.0780</td>
<td style="text-align: right;">0.0979</td>
<td style="text-align: right;">1.4415</td>
<td style="text-align: right;">92.23</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>10</strong></td>
<td style="text-align: right;">20.69</td>
<td style="text-align: right;">0.7095</td>
<td style="text-align: right;">0.2758</td>
<td style="text-align: right;">0.0889</td>
<td style="text-align: right;">0.5866</td>
<td style="text-align: right;">72.49</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="exploratory-analysis" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-analysis">3.4 Exploratory Analysis</h3>
<p>Unlike the primary and secondary analyses above, the following tests were exploratory rather than confirmatory. These tests are intended to generate hypotheses for future investigation rather than to test pre-determined predictions. Therefore, no correction for multiple comparisons was applied, and results should be interpreted with appropriate caution.</p>
<section id="slot-position-and-minigame-selection" class="level4">
<h4 class="anchored" data-anchor-id="slot-position-and-minigame-selection">3.4.1 Slot Position and Minigame Selection</h4>
<p>A chi-square test of independence was conducted to explore whether there was an association between slot positions and minigame selections. Since the lowest cell count was 961, assumptions of the standard chi-square test were satisfied. The test indicated there was a statistically significant association between slot position and minigame selection, <span class="math inline">\(\chi^2\)</span> (175) = 221.81, <span class="math inline">\(p\)</span> = 0.0096. However, the effect size was calculated to be negligible (Cramér’s <span class="math inline">\(V\)</span> = 0.0346), which is well below the conventional thresholds for even a small effect. While this suggests that slot positions and minigame selections may not be fully independent, the magnitude of this association is likely trivial. The low p value may be attributable to the large sample size providing high statistical power to detect minor deviations rather than a meaningful relationship.</p>
</section>
<section id="temporal-patterns-in-minigame-selection" class="level4">
<h4 class="anchored" data-anchor-id="temporal-patterns-in-minigame-selection">3.4.2 Temporal Patterns in Minigame Selection</h4>
<p>Another chi-square test of independence was conducted to explore if there was an association between the hour of day and minigame selection. Data were collected across six different hours of the day (11:00–16:59). Since the lowest cell count was 1552, assumptions of the standard chi-square test were satisfied. The test indicated that there was no significant association between the hour of day and minigame selection, <span class="math inline">\(\chi^2\)</span> (125) = 76.1, <span class="math inline">\(p\)</span> = 0.9998. The Cramér’s <span class="math inline">\(V\)</span> was also calculated to be 0.0239, meaning that the effect size is also negligible, supporting the non-significant p value.</p>
</section>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">4 Discussion</h2>
<p>This study examined whether minigame selection in <em>Hypixel Party Games</em> behaves consistently with a uniform random process, using combined and individual-trial goodness of fit tests. Across the combined dataset and all 10 individual trials, none showed a statistically significant deviation from uniform minigame selection. Exploratory analyses found a statistically significant, but practically negligible, correlation between slot and minigame selection, and no significant association between the hour of day and minigame selection.</p>
<section id="interpretation-of-primary-and-secondary-results" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-primary-and-secondary-results">4.1 Interpretation of Primary and Secondary Results</h3>
<p>The consistency of the results in the combined dataset strengthens confidence that the minigame selection behaves as a uniform random process. As well, the consistency observed across analyzing the 10 individual trials further supported the idea that <span class="math inline">\(H_0\)</span> is true, rather than the apparent distribution relying on aggregating enough data to average out inconsistencies. This distinction has practical significance: if individual trials had shown meaningfully different behavior from the combined result, it would suggest the selection mechanism may behave unpredictably or inconsistently under certain external conditions. This would undermine the player’s trust even if the aggregated data looked consistent on average. The fact that none of the trials nor the combined dataset showed a meaningful deviation from <span class="math inline">\(H_0\)</span>, and the pattern matched what would be expected from a properly designed uniform random draw, supports the conclusion that the underlying selection algorithm is consistent with a uniform random process.</p>
</section>
<section id="interpretation-of-exploratory-findings" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-exploratory-findings">4.2 Interpretation of Exploratory Findings</h3>
<p>The exploratory findings represent a useful illustration of a common pitfall in statistical interpretation: a result can still be statistically significant, while being practically meaningless, due to the high power that large sample sizes provide in order to detect trivial deviations. Rather than suggesting a genuine design flaw or bias in how minigames are assigned to slot positions, the slot-position finding more likely reflects the sensitivity of chi-square tests at scale. This distinction is worth highlighting as a reading of just the p value alone without the effect size could lead to an unwarranted claim that the video game’s slot assignment is meaningfully biased, when the actual magnitude of this bias is completely negligible. This highlights the importance of reporting effect sizes along with significant p values, especially in exploratory work where a significant result may be misinterpreted.</p>
</section>
<section id="limitations" class="level3">
<h3 class="anchored" data-anchor-id="limitations">4.3 Limitations</h3>
<p>Several limitations should be considered when interpreting these results. Firstly, the most important limitation is that the structure of a game introduces dependence between observations, violating a core assumption of the chi-square goodness of fit test. While this was addressed in the primary and secondary analyses through a Monte Carlo simulation designed to approximate the correct null distribution under this dependence structure, this correction relies on the assumption that the simulation accurately mirrors the true selection mechanism. Any possible unmodeled or inaccurate aspect of the Monte Carlo simulation could make the p values and effect sizes reported unreliable.</p>
<p>Additionally, while the 10 trials examined in this study were collected independently in the sense of being separate data collection sessions, they might not fully represent other possible underlying conditions (e.g., different players, time period, etc.). Demonstrating consistency across trials under similar circumstances shows that the selection process behaves reliably under those specific conditions, but does not establish that this consistency would transfer to other varied contexts.</p>
<p>Finally, the exploratory analyses which analyzed slot and hour of day were not corrected for multiple comparisons nor for the same dependence structure addressed in the primary and secondary analyses. Therefore, the results may introduce inaccuracy into this analysis, and should be treated with appropriate caution.</p>
</section>
<section id="future-directions" class="level3">
<h3 class="anchored" data-anchor-id="future-directions">4.4 Future Directions</h3>
<p>Several directions for future research can follow directly from the limitations discussed above. First, since the Monte Carlo correction used in this study relies on the assumption that the simulation accurately reflects the actual selection mechanism, future work could try to validate and strengthen this assumption by applying additional, independent statistical tests that assess different notions of randomness. A possible statistical test that could be performed could be a categorical serial test to determine whether a certain minigame selection changes the probability of a future minigame being chosen. Agreement across multiple, methodologically distinct tests would provide stronger indirect evidence of genuine randomness than a single test would establish on its own.</p>
<p>Second, because the 10 trials in this study may not have captured different underlying conditions, future studies could deliberately collect data across a wider range of contexts. Some examples could include collecting data using different accounts, playing at a larger variety of hours, and playing on different versions. These different circumstances could influence the results collected and confirm whether the consistency observed holds more broadly, or if it is only specific to the conditions to which this data was collected.</p>
<p>Finally, the exploratory analyses, particularly the slot and minigame selection analysis, could warrant a follow-up study. Such a study could be designed specifically to test this relationship as a primary hypothesis, with an appropriately corrected significance threshold and a Monte Carlo correction accounting for the same dependence structure addressed in the primary and secondary analyses. This would allow for a more conclusive determination of whether this association reflects a genuine, reproducible pattern.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">5 Conclusion</h2>
<p>This study investigated whether the minigame selection system in <em>Hypixel Party Games</em> produced outcomes consistent with random selection. It was found that there were no statistically significant deviations from an expected uniform distribution, supporting <span class="math inline">\(H_0\)</span> with both the individual trials and combined dataset. These findings carry a broader significance beyond this specific game; humans are prone to the clustering illusion, which is a specific form of apophenia: the broader tendency to perceive meaningful patterns in random data. The clustering illusion specifically refers to random streaks or repeated outcomes that are mistakenly interpreted as evidence of an underlying pattern or bias, possibly leading players to believe that a video game is biased toward certain outcomes. Without rigorous statistical testing, such perceptions can go unchallenged, potentially shaping player trust or behavior based on an illusion rather than evidence. This experiment demonstrates how statistical methods can directly address that gap, offering an objective standard to test these perceptions.</p>
<p>Although this study focused on a singular video game, the methods used could be applicable to many other randomized systems, such as lotteries, shuffling algorithms, or any process claiming fairness through randomness. Statistical analysis provides an objective way to distinguish genuine bias from patterns that random variation may produce, allowing claims of randomness to be evaluated accurately. In systems where fairness and trust depend on genuine randomness, this kind of rigorous testing offers a meaningful safeguard against both unfounded suspicion and undetected bias alike.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>